# Generated by Django 5.0.4 on 2024-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_location_business_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
